### ISSUE TITLE
Passing parameters to Black Duck

### ISSUE THREAD

**Issue by dimklose** [synopsys-sig/synopsys-action#107]
Hello,

since I was not able to find it in the documentation - how can I pass the following parameters to Black Duck using your action?

DETECT_PROJECT_VERSION_NAME
DETECT_PROJECT_NAME
DETECT_NPM_DEPENDENCY_TYPES_EXCLUDED
DETECT_INCLUDED_DETECTOR_TYPES
DETECT_SOURCE_PATH

Thanks in advance.

**Comment by sig-tithi** [comment]
As mentioned in readme, detect parameters can be passed as environment variables in action.yml like
env:
  DETECT_PROJECT_VERSION_NAME
https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow

**Comment by lejouni** [comment]
You can use all detect params from https://community.synopsys.com/s/document-item?bundleId=integrations-detect&topicId=properties/all-properties.html&_LANG=enus, you just need to give them with uppercase and dots replace with underscore. So, to set the detect to trust all certs, you need to give blackduck.trust.cert=true -> BLACKDUCK_TRUST_CERT: 'true' as an env. variable.

**Comment by dimklose** [comment]
This did the trick, thank you.

**Comment by dimklose** [comment]
This did the trick, thank you.
