### ISSUE TITLE
blackduck_automation_prcomment with GitHub Enterprise

### ISSUE THREAD

**Issue by Carsten87** [synopsys-sig/synopsys-action#111]
How can I configure the synopsys-action to work with GitHub Enterprise? If I set `blackduck_automation_prcomment: true` the action tries to communicate with github.com instead of the GH Enterprise instance the action is running on which obviously fails.

I think the action itself should figure out where it is running and select the appropriate API endpoint accordingly.

~~~txt
2023-06-16 10:34:37.7338 CEST [GitHub Commenter] INFO: will use default GitHub API URL "https://api.github.com/", as "github.api.url" is not configured
2023-06-16 10:34:37.9617 CEST [GitHub Commenter] ERROR: authorization failure - please check if the value configured for "github.user.token" has appropriate permissions: Bad credentials: Received unexpected response status code '401 Unauthorized' from GitHub API
2023-06-16 10:34:37.9874 CEST [GitHub Commenter] ERROR: Adapter failed: exit status 1
Error: Workflow failed! Exit Code: 2 Error from adapter end
~~~

**Comment by tvcsantos** [comment]
Actually there is no need for a custom input parameter the API URL is already provided out-of-the-box in GitHub actions context by the env variable GITHUB_API_URL.

**Comment by sig-tithi** [comment]
We are working on it and fix will be available sometime next month.

**Comment by tvcsantos** [comment]
> We are working on it and fix will be available sometime next month.

Nice 👍 . Thanks for the feedback

**Comment by continental-admin** [comment]
I just tried the fix from #115 and ran into a new/related problem:
now the inital error is gone but I see a new one.
```
2023-08-18 14:27:59.0516 UTC [GitHub Commenter] ERROR: Not Found: Received unexpected response status code '404 Not Found' from GitHub API
```
The question is: How is the PR comment URL built?
I am running from a PR triggered workflow, so the URL should be somewhere in the GitHub Action's environment variables.
![image](https://github.com/synopsys-sig/synopsys-action/assets/39406523/a6e18b2f-10de-4603-8b5e-dfc5d6c64a7f)

I am also messing with the default project name and version in Blackduck, could that be a problem for the URL? @tvcsantos did you use the default settings or also an updated one?
```
          DETECT_PROJECT_NAME: ${{ github.server_url }}/${{ github.repository }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.sha }}
```

**Comment by ToWi87** [comment]
Hello @tvcsantos,
I just tried to verify your fix, but am running in a new problem:
`[GitHub Commenter] ERROR: Not Found: Received unexpected response status code '404 Not Found' from GitHub API`

What settings did you run this so it worked? I didn't change anything beside using your PR's code.

**Comment by tvcsantos** [comment]
> Hello @tvcsantos, I just tried to verify your fix, but am running in a new problem: `[GitHub Commenter] ERROR: Not Found: Received unexpected response status code '404 Not Found' from GitHub API`
> 
> What settings did you run this so it worked? I didn't change anything beside using your PR's code.

Hey @ToWi87, we are facing the same problem. This PR only addresses the URL change. Since synopsys uses bridge to to the remaining steps and bridge is a blackbox and I don't have access to the code I was not able to investigate further :(.

**Comment by gonmmarques** [comment]
> We are working on it and fix will be available sometime next month.

Hey hello, by any chance can you please share when this might be available? Thanks

**Comment by gonmmarques** [comment]
> We are working on it and fix will be available sometime next month.

Hello again, we are already mid September, any ETA here?

**Comment by sig-tithi** [comment]
@gonmmarques - Apologies for the delay. We couldn't look into or verify this issue during our past release due to some infrastructure issue on our end and also other priority items. We will look into this and keep you posted.

**Comment by ToWi87** [comment]
Hello again,
after seeing this: https://github.com/synopsys-sig/synopsys-action/releases/tag/v1.5.0
I briefly tried to run this with `blackduck_automation_prcomment: true`

Here my feedback:
```
Run synopsys-sig/synopsys-action@v1.5.0
Synopsys Action started...
Blackduck Automation comment is enabled
Error: Workflow failed! Missing required github token for fix pull request/automation comment
```
And then the whole `step` is killed.

My GH Action config is (as of https://sig-product-docs.synopsys.com/bundle/bridge/page/documentation/c_additional-github-parameters.html)
set to
![image](https://github.com/synopsys-sig/synopsys-action/assets/19682656/d550df6d-df3e-4eba-8de2-adedfcd9ea3a)

Can someone confirm this?

**Comment by ToWi87** [comment]
update from myself:
```
with:
  github_token: ${{ github.token }} (instead of secrets.GITHUB_TOKEN as mentioned in the docs)
```
I am back to my initial `404` report: https://github.com/synopsys-sig/synopsys-action/issues/111#issuecomment-1684027951

**Comment by sig-tithi** [comment]
The fix is not yet available, we are working with our internal teams to prioritise it.

**Comment by benlamm-abi** [comment]
Any updates here? May be there is already a prediction for the release date of the fix, so that we can better plan further steps? What is the official workaround? Using Detect Rapid Scan Action?

**Comment by sig-tithi** [comment]
> Any updates here? May be there is already a prediction for the release date of the fix, so that we can better plan further steps? What is the official workaround? Using Detect Rapid Scan Action?

- Please try with latest 1.6.0 version for PR comment support for GitHub Enterprise environment

**Comment by Carsten87** [comment]
I can confirm that it works on my end now.
